- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  vars:
    brew_taps:
      - homebrew/core
      - caskroom/cask
    brew_cask_apps:
      - alfred
      - docker
      - firefox
      - google-chrome
      - google-japanese-ime
      - iterm2
    brew_packages:
      - neovim
      - rbenv
      - pyenv
      - nodebrew
      - awscli
      - bash-completion
      - fish
      - docker
      - docker-compose
      - git
      - jq
      - openssl
      - tig
      - tree
      - curl
      - ssh
      - sshrc
      - tmux
 
  tasks:
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_tap_module.html
    - name: Homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"
 
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_cask_module.html
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_apps }}"
 
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
 
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
