- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  vars:
    brew_taps:
      - homebrew/core
      - caskroom/cask
    brew_cask_apps:
      - alfred
      - docker
      - firefox
      - google-chrome
      - google-japanese-ime
      - iterm2
      - java
      - inkdrop
      - 1password
      - intellij-idea
      - dropbox
    brew_packages:
      - neovim
      - rbenv
      - ruby-build
      - pyenv
      - jenv
      - nodebrew
      - awscli
      - bash-completion
      - fish
      - docker
      - docker-compose
      - git
      - jq
      - ag
      - httpie
      - openssl
      - tig
      - tree
      - curl
      - sshrc
      - tmux

  tasks:
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_tap_module.html
    - name: Homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_cask_module.html
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_apps }}"
      ignore_errors: yes

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
      ignore_errors: yes

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
      ignore_errors: yes

    - name: Install Python3
      shell: pyenv install 3.5.2
      ignore_errors: yes

    - name: Install Python
      shell: pyenv install 2.7.12
      ignore_errors: yes

    - name: Set Python Global
      shell: pyenv global 3.5.2
      ignore_errors: yes

    - name: Install Ruby
      shell: rbenv install 2.5.0
      ignore_errors: yes

    - name: Set Ruby Global
      shell: rbenv global 2.5.0
      ignore_errors: yes
